// components/HiddenAnchor.vue
<template>
    <button @click="handleClick" class="hidden-anchor fixed top-0 bg-green text-white shadow-light dark:shadow-heavy p-card font-bold text-xl tiny:text-lg z-50">
        <slot></slot>
    </button>
</template>

<script setup lang="ts">
const props = defineProps<{
    el: HTMLInputElement | null;
}>();

const handleClick = () => {
    if (props.el === null)
        return;

    props.el.scrollIntoView({ behavior: "smooth" });
    props.el.focus({ preventScroll: true });
    props.el.blur();
}
</script>

<style scoped lang="scss">
.hidden-anchor {
    transform: translate(-50%, -200px);
	transition: transform 0.3s;

    @media (prefers-reduced-motion) {
        transition: none;
    }

    &:focus {
        transform: translate(-50%, 20px);
    }
}
</style>

// src/components/HiddenAnchor.tsx
interface HiddenAnchorProps {
    to: string;
}

export default function HiddenAnchor({ to }: HiddenAnchorProps) {
    const handleClick = () => {
        const element = document.getElementById(to);

        if (element == null) return;

        element.scrollIntoView({ behavior: "smooth" });
        element.focus({ preventScroll: true });
        element.blur();
    };

    return (
        <button
            onClick={handleClick}
            className="bg-primary shadow-light tiny:text-base fixed top-0 z-50 -translate-x-2/4 -translate-y-52 px-6 py-4 text-lg font-bold text-white transition-transform focus:translate-y-5 motion-reduce:transition-none"
        >
            Skip to {to}
        </button>
    );
}
